# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AES(object):
    def setupUi(self, AES):
        AES.setObjectName("AES")
        AES.resize(956, 718)
        self.centralwidget = QtWidgets.QWidget(AES)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_menu.setStyleSheet("QFrame{\n"
"    background-color:rgb(220, 220, 220)\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_menu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_saes_enc = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_saes_enc.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    border-radius:9px;\n"
"    height:35px;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_saes_enc.setObjectName("pushButton_saes_enc")
        self.verticalLayout.addWidget(self.pushButton_saes_enc)
        self.pushButton_saes_dec = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_saes_dec.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_saes_dec.setObjectName("pushButton_saes_dec")
        self.verticalLayout.addWidget(self.pushButton_saes_dec)
        self.pushButton_asc_enc = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_asc_enc.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_asc_enc.setObjectName("pushButton_asc_enc")
        self.verticalLayout.addWidget(self.pushButton_asc_enc)
        self.pushButton_asc_dec = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_asc_dec.setAutoFillBackground(False)
        self.pushButton_asc_dec.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_asc_dec.setObjectName("pushButton_asc_dec")
        self.verticalLayout.addWidget(self.pushButton_asc_dec)
        self.pushButton_double_enc = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_double_enc.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_double_enc.setObjectName("pushButton_double_enc")
        self.verticalLayout.addWidget(self.pushButton_double_enc)
        self.pushButton_double_dec = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_double_dec.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_double_dec.setObjectName("pushButton_double_dec")
        self.verticalLayout.addWidget(self.pushButton_double_dec)
        self.pushButton_triple_enc = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_triple_enc.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_triple_enc.setObjectName("pushButton_triple_enc")
        self.verticalLayout.addWidget(self.pushButton_triple_enc)
        self.pushButton_triple_dec = QtWidgets.QPushButton(self.frame_menu)
        self.pushButton_triple_dec.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_triple_dec.setObjectName("pushButton_triple_dec")
        self.verticalLayout.addWidget(self.pushButton_triple_dec)
        self.horizontalLayout.addWidget(self.frame_menu)
        self.frame_content = QtWidgets.QFrame(self.centralwidget)
        self.frame_content.setStyleSheet("QFrame{\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.lineEdit_input = QtWidgets.QLineEdit(self.frame_content)
        self.lineEdit_input.setGeometry(QtCore.QRect(189, 70, 461, 80))
        self.lineEdit_input.setStyleSheet("QLineEdit{\n"
"    border:1 solid px;\n"
"    border-radius:9px;\n"
"}")
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.lineEdit_key = QtWidgets.QLineEdit(self.frame_content)
        self.lineEdit_key.setGeometry(QtCore.QRect(189, 290, 461, 80))
        self.lineEdit_key.setStyleSheet("QLineEdit{\n"
"    border:1 solid px;\n"
"    border-radius:9px;\n"
"}")
        self.lineEdit_key.setObjectName("lineEdit_key")
        self.label_input = QtWidgets.QLabel(self.frame_content)
        self.label_input.setGeometry(QtCore.QRect(10, 60, 131, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_input.setFont(font)
        self.label_input.setObjectName("label_input")
        self.label_key = QtWidgets.QLabel(self.frame_content)
        self.label_key.setGeometry(QtCore.QRect(20, 310, 121, 50))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_key.setFont(font)
        self.label_key.setObjectName("label_key")
        self.label_out = QtWidgets.QLabel(self.frame_content)
        self.label_out.setGeometry(QtCore.QRect(10, 540, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_out.setFont(font)
        self.label_out.setObjectName("label_out")
        self.textBrowser_output = QtWidgets.QTextBrowser(self.frame_content)
        self.textBrowser_output.setGeometry(QtCore.QRect(190, 530, 461, 80))
        self.textBrowser_output.setStyleSheet("QText_Brower{\n"
"border:2 solid px;\n"
"    border-radius:9px;\n"
"    \n"
"}")
        self.textBrowser_output.setObjectName("textBrowser_output")
        self.pushButton_attack = QtWidgets.QPushButton(self.frame_content)
        self.pushButton_attack.setGeometry(QtCore.QRect(40, 650, 280, 35))
        self.pushButton_attack.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    border: 2px solid black;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_attack.setObjectName("pushButton_attack")
        self.pushButton_attack_2 = QtWidgets.QPushButton(self.frame_content)
        self.pushButton_attack_2.setGeometry(QtCore.QRect(40, 650, 280, 35))
        self.pushButton_attack_2.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    border: 2px solid black;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_attack_2.setObjectName("pushButton_attack_2")
        self.pushButton_attack_3 = QtWidgets.QPushButton(self.frame_content)
        self.pushButton_attack_3.setGeometry(QtCore.QRect(360, 650, 280, 35))
        self.pushButton_attack_3.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    border: 2px solid black;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_attack_3.setObjectName("pushButton_attack_3")
        self.pushButton_attack_4 = QtWidgets.QPushButton(self.frame_content)
        self.pushButton_attack_4.setGeometry(QtCore.QRect(360, 650, 280, 35))
        self.pushButton_attack_4.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    border: 2px solid black;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_attack_4.setObjectName("pushButton_attack_4")
        self.pushButton_attack_5 = QtWidgets.QPushButton(self.frame_content)
        self.pushButton_attack_5.setGeometry(QtCore.QRect(40, 650, 280, 35))
        self.pushButton_attack_5.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    border: 2px solid black;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_attack_5.setObjectName("pushButton_attack_5")
        self.pushButton_attack_6 = QtWidgets.QPushButton(self.frame_content)
        self.pushButton_attack_6.setGeometry(QtCore.QRect(360, 650, 280, 35))
        self.pushButton_attack_6.setStyleSheet("QPushButton:hover\n"
"{\n"
"    background-color:rgb(44 , 137 , 255);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"QPushButton{\n"
"    height:35px;\n"
"    border-radius:9px;\n"
"    border: 2px solid black;\n"
"    background-color:rgb(255, 255, 255)\n"
"}")
        self.pushButton_attack_6.setObjectName("pushButton_attack_6")
        self.horizontalLayout.addWidget(self.frame_content)
        AES.setCentralWidget(self.centralwidget)

        self.retranslateUi(AES)
        QtCore.QMetaObject.connectSlotsByName(AES)

    def retranslateUi(self, AES):
        _translate = QtCore.QCoreApplication.translate
        AES.setWindowTitle(_translate("AES", "MainWindow"))
        self.pushButton_saes_enc.setText(_translate("AES", "S-AES加密(16bits密钥)"))
        self.pushButton_saes_dec.setText(_translate("AES", "S-AES解密(16bits密钥)"))
        self.pushButton_asc_enc.setText(_translate("AES", "ASCII码加密"))
        self.pushButton_asc_dec.setText(_translate("AES", "ASCII码解密"))
        self.pushButton_double_enc.setText(_translate("AES", "双重加密(32bits密钥)"))
        self.pushButton_double_dec.setText(_translate("AES", "双重解密(32bits密钥)"))
        self.pushButton_triple_enc.setText(_translate("AES", "三重加密（48bits密钥）"))
        self.pushButton_triple_dec.setText(_translate("AES", "三重解密（48bits密钥）"))
        self.label_input.setText(_translate("AES", "<html><head/><body><p><span style=\" font-size:10pt;\">输入</span></p><p><span style=\" font-size:10pt;\">密文/明文：</span></p></body></html>"))
        self.label_key.setText(_translate("AES", "<html><head/><body><p><span style=\" font-size:10pt;\">密钥：</span></p></body></html>"))
        self.label_out.setText(_translate("AES", "<html><head/><body><p><span style=\" font-size:10pt;\">输出</span></p><p><span style=\" font-size:10pt;\">明文/密文：</span></p></body></html>"))
        self.pushButton_attack.setText(_translate("AES", "进入求密钥模式"))
        self.pushButton_attack_2.setText(_translate("AES", "退出求密钥模式"))
        self.pushButton_attack_3.setText(_translate("AES", "求解密钥"))
        self.pushButton_attack_4.setText(_translate("AES", "进入CBC模式"))
        self.pushButton_attack_5.setText(_translate("AES", "退出CBC模式"))
        self.pushButton_attack_6.setText(_translate("AES", "CBC加密"))
